# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'ubuntu-latest'

container: 'rocker/r-ver:latest'

steps:
- script: Rscript install2.r devtools
  displayName: 'devtools install'
  continueOnError: true

- script: Rscript -e 'devtools::check(cran = FALSE)'
  displayName: 'Package Check'
  continueOnError: true

- script: Rscript -e 'sessionInfo()'
  displayName: 'R Version'
